version: '3.8'


services:

  frontend:
    image: ghcr.io/smd-ka/hoffnungstage-2026/frontend:main
    build:
      context: ./
      dockerfile: ../frontend/Dockerfile
    networks:
      default: {}
      caddy_net:
        aliases:
          - hoffnungstage-2026_entrypoint
    restart: always


networks:
  default:
    driver: bridge
  caddy_net:
    name: caddy_net
    external: true
